export const SETTINGS_STORE = "opencode.settings"
export const DEFAULT_SERVER_URL_KEY = "defaultServerUrl"
export const WSL_SERVERS_KEY = "wslServers"
export const PINCH_ZOOM_ENABLED_KEY = "pinchZoomEnabled"
export const SERVER_PORT_KEY = "serverPort"
export const SERVER_USERNAME_KEY = "serverUsername"
export const SERVER_PASSWORD_KEY = "serverPassword"
